In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/crop-production-statistics-from-1997-in-india/apy.csv


In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from pandas_profiling import ProfileReport

In [3]:
df=pd.read_csv("/kaggle/input/crop-production-statistics-from-1997-in-india/apy.csv")

In [4]:
profile = ProfileReport(df, title="Pandas Profiling Report")

In [5]:
df.head()

State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    

                  Crop    Area  Production  
0             Arecanut  1254.0      2000.0  
1  Other Kharif pulses     2.0         1.0  
2                 Rice   102.0       321.0  
3               Banana   176.0       641.0  
4            Cashewnut   720.0       165.0

In [6]:
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.shape

(246091, 7)

In [8]:
# Dimensions of the dataset is 246091 rows and 7 columns

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   State_Name     246091 non-null  object 
 1   District_Name  246091 non-null  object 
 2   Crop_Year      246091 non-null  int64  
 3   Season         246091 non-null  object 
 4   Crop           246091 non-null  object 
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB


**** Out of seven variables, we have four categorical variables(State_Name , District_Name , Season & Crop type) * and 
* three continuous variables in float(Area and Production) and integer(Crop_Year) format. ****

In [10]:
# Checking for Missing Data
df.isnull().sum()

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

In [11]:
3730/246091

0.015156994770227274

In [12]:
# Checking for missing values showed Production variable showing huge number of missing values amounting to 3730 values and no missing values for other variables.
# Next step :-
#       dropping these samples as we have sufficiently big dataset. 
#         Missing value accounts for only 1.5% of total sample size.
df.dropna(subset=["Production"],axis=0,inplace=True)

In [13]:
#By dropping missing values in Production variable we ended up with 242361 sample size.
df.isnull().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [14]:
#Checking for Correlation between variables

In [15]:
plt.tick_params(labelsize=10)
sns.heatmap(df.corr(),annot=True)

<AxesSubplot:>

 ** CONCLUSION FROM THE CORELATION **:-
1.    * There is no variable showing high correlation with any other variable in the dataset *.

# UNIVARIATE ANALYSIS 
-----------------------
# 1) STATE VARIABLE

In [16]:
df.State_Name.unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir ', 'Jharkhand',
       'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana ',
       'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
      dtype=object)

In [17]:
df.State_Name.nunique()

33

This dataset encodes agriculture data for 33 Indian states (including Union Territory). DataFrame.value_counts() helps to see the quantum of levels present. As seen below, we have more data from top agriculture rich states like Uttar Pradesh, Madhya Pradesh and Karnatake than other states.

In [18]:
df.State_Name.value_counts()

Uttar Pradesh                  33189
Madhya Pradesh                 22604
Karnataka                      21079
Bihar                          18874
Assam                          14622
Odisha                         13524
Tamil Nadu                     13266
Maharashtra                    12496
Rajasthan                      12066
Chhattisgarh                   10368
West Bengal                     9597
Andhra Pradesh                  9561
Gujarat                         8365
Telangana                       5591
Uttarakhand                     4825
Haryana                         4540
Kerala                          4003
Nagaland                        3904
Punjab                          3143
Meghalaya                       2867
Arunachal Pradesh               2545
Himachal Pradesh                2456
Jammu and Kashmir               1632
Tripura                         1412
Manipur                         1266
Jharkhand                       1266
Mizoram                          954
P

**This dataset encodes agriculture data for 33 Indian states (including Union Territory). 
 DataFrame.value_counts() helps to see the quantum of levels present. **
 As seen below:- 
 we have more data from top agriculture rich states like Uttar Pradesh, Madhya Pradesh and Karnatake than other states.

# 2) DISTRICT VARIABLE


In [19]:
df.District_Name.nunique()

646

* For 33 Indain states on further dissecting we get data for 646 different districts.

In [20]:
df.District_Name.unique()

array(['NICOBARS', 'NORTH AND MIDDLE ANDAMAN', 'SOUTH ANDAMANS',
       'ANANTAPUR', 'CHITTOOR', 'EAST GODAVARI', 'GUNTUR', 'KADAPA',
       'KRISHNA', 'KURNOOL', 'PRAKASAM', 'SPSR NELLORE', 'SRIKAKULAM',
       'VISAKHAPATANAM', 'VIZIANAGARAM', 'WEST GODAVARI', 'ANJAW',
       'CHANGLANG', 'DIBANG VALLEY', 'EAST KAMENG', 'EAST SIANG',
       'KURUNG KUMEY', 'LOHIT', 'LONGDING', 'LOWER DIBANG VALLEY',
       'LOWER SUBANSIRI', 'NAMSAI', 'PAPUM PARE', 'TAWANG', 'TIRAP',
       'UPPER SIANG', 'UPPER SUBANSIRI', 'WEST KAMENG', 'WEST SIANG',
       'BAKSA', 'BARPETA', 'BONGAIGAON', 'CACHAR', 'CHIRANG', 'DARRANG',
       'DHEMAJI', 'DHUBRI', 'DIBRUGARH', 'DIMA HASAO', 'GOALPARA',
       'GOLAGHAT', 'HAILAKANDI', 'JORHAT', 'KAMRUP', 'KAMRUP METRO',
       'KARBI ANGLONG', 'KARIMGANJ', 'KOKRAJHAR', 'LAKHIMPUR', 'MARIGAON',
       'NAGAON', 'NALBARI', 'SIVASAGAR', 'SONITPUR', 'TINSUKIA',
       'UDALGURI', 'ARARIA', 'ARWAL', 'AURANGABAD', 'BANKA', 'BEGUSARAI',
       'BHAGALPUR', 'BHOJPUR', 'B

In [21]:
df.District_Name.value_counts()

TUMKUR       931
BELGAUM      924
BIJAPUR      905
HASSAN       895
BELLARY      887
            ... 
HYDERABAD      8
KHUNTI         6
RAMGARH        6
NAMSAI         1
MUMBAI         1
Name: District_Name, Length: 646, dtype: int64

On District front, we have have more data coming from Tumkur, Belgaum, Hassan, Bellary and Bijapur from Karantaka state.

#  OBSERVATION from District dataset:- 
 **We have have more data coming from **"Tumkur" , "Belgaum" , "Hassan" , "Bellary" and "Bijapur"from Karantaka state.*

# 3) CROP YEAR VARIABLE

Our Dataset has data for 19 years from 1997 to 2015. Top years are 2003, 2002, 2007-08 and 2006.

In [22]:
print(df.Crop_Year.nunique())
print(df.Crop_Year.min())
print(df.Crop_Year.max())
print(df.Crop_Year.value_counts())

19
1997
2015
2003    17139
2002    16536
2007    14269
2008    14230
2006    13976
2004    13858
2010    13793
2011    13791
2009    13767
2000    13553
2005    13519
2013    13475
2001    13293
2012    13184
1999    12441
1998    11262
2014    10815
1997     8899
2015      561
Name: Crop_Year, dtype: int64


# 4) SEASON VARIABLE

This Dataset reflects the data of six different seasons i.e. 
Kharif, Annual, Autumn, Rabi, Summer and Winter crops with more crops 
yielding in Winter.

 Frequency wise, we have more data from Kharif,Rabi and Annual crop types.

 ADDITIONAL INFORMATION:-
 ----------------------------

 Kharif crop season:- July –October during the south-west monsoon.
 Rabi crop season :- October-March (winter).
 Summer crops season :- Between March and June.

 Crops in India are dependent on Monsoon water. 
 There will be variation in crop production from one year to another.

In [23]:
print(df.Season.nunique())
print(df.Season.unique())
print(df.Season.max())
print(df.Season.value_counts())

6
['Kharif     ' 'Whole Year ' 'Autumn     ' 'Rabi       ' 'Summer     '
 'Winter     ']
Winter     
Kharif         94283
Rabi           66160
Whole Year     56127
Summer         14811
Winter          6050
Autumn          4930
Name: Season, dtype: int64


Dataset shows data for 124 different crop varieties. 
> On doing df.value_counts(), we can show top crops are Rice(15082),Maize(13787) and Moong(Green Gram, 10106).

In [24]:

print(df.Crop.nunique())
print(df.Crop.unique())
print(df.Crop.max())
print(df.Crop.value_counts().head(20))

124
['Arecanut' 'Other Kharif pulses' 'Rice' 'Banana' 'Cashewnut' 'Coconut '
 'Dry ginger' 'Sugarcane' 'Sweet potato' 'Tapioca' 'Black pepper'
 'Dry chillies' 'other oilseeds' 'Turmeric' 'Maize' 'Moong(Green Gram)'
 'Urad' 'Arhar/Tur' 'Groundnut' 'Sunflower' 'Bajra' 'Castor seed'
 'Cotton(lint)' 'Horse-gram' 'Jowar' 'Korra' 'Ragi' 'Tobacco' 'Gram'
 'Wheat' 'Masoor' 'Sesamum' 'Linseed' 'Safflower' 'Onion'
 'other misc. pulses' 'Samai' 'Small millets' 'Coriander' 'Potato'
 'Other  Rabi pulses' 'Soyabean' 'Beans & Mutter(Vegetable)' 'Bhindi'
 'Brinjal' 'Citrus Fruit' 'Cucumber' 'Grapes' 'Mango' 'Orange'
 'other fibres' 'Other Fresh Fruits' 'Other Vegetables' 'Papaya'
 'Pome Fruit' 'Tomato' 'Mesta' 'Cowpea(Lobia)' 'Lemon' 'Pome Granet'
 'Sapota' 'Cabbage' 'Rapeseed &Mustard' 'Peas  (vegetable)' 'Niger seed'
 'Bottle Gourd' 'Varagu' 'Garlic' 'Ginger' 'Oilseeds total' 'Pulses total'
 'Jute' 'Peas & beans (Pulses)' 'Blackgram' 'Paddy' 'Pineapple' 'Barley'
 'Sannhamp' 'Khesari' 'Guar seed' 'Mo

 Dataset shows data for 124 different crop varieties. 
 ---------------------------------------------------
 On doing df.value_counts(),  OUTPUTS :-
                                         **1) Rice(15082),
                                         2) Maize(13787) and 
                                         3) Moong(Green Gram, 10106).**

# Area Variable: To find the "Area under cultivation"

In [25]:
print(df.Area.nunique())
print(df.Area.max())
print(df.Area.value_counts().head(10))
print(df.Area.value_counts().tail(10))

38391
8580100.0
1.0      3573
2.0      3140
100.0    2621
3.0      2478
4.0      2182
5.0      2090
6.0      1750
200.0    1671
10.0     1590
7.0      1555
Name: Area, dtype: int64
63107.0     1
13655.0     1
95399.0     1
71644.0     1
17459.0     1
25569.0     1
19349.0     1
90302.0     1
39698.0     1
279151.0    1
Name: Area, dtype: int64


**We have proportion of area under cultivation for different states and districts. Production depends on the proportion of area allocated for cultivation.

**

# "Production Variable"

In [26]:
df.Production.describe()

count    2.423610e+05
mean     5.825034e+05
std      1.706581e+07
min      0.000000e+00
25%      8.800000e+01
50%      7.290000e+02
75%      7.023000e+03
max      1.250800e+09
Name: Production, dtype: float64

Production values range from 0 to 1250800000

In [27]:
df.Production.max()

1250800000.0

In [28]:
df.Production.value_counts(ascending = False)

1.000000e+00    4028
0.000000e+00    3523
1.000000e+02    3521
2.000000e+00    2964
3.000000e+00    2311
                ... 
2.120000e+08       1
1.070000e+00       1
2.293410e+05       1
1.870600e+04       1
5.978990e+05       1
Name: Production, Length: 51627, dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242361 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   State_Name     242361 non-null  object 
 1   District_Name  242361 non-null  object 
 2   Crop_Year      242361 non-null  int64  
 3   Season         242361 non-null  object 
 4   Crop           242361 non-null  object 
 5   Area           242361 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 14.8+ MB


**Looking at distribution of Area and Production variables. These two variables are highly skewed with lot of outliers.**

> An outlier is an observation that lies an abnormal distance from other values in a random sample from a population

In [30]:
plt.boxplot(df.Area);

In [31]:
plt.boxplot(df.Production);

# BIVARIATE ANALYSIS

In [32]:
Prod = df.groupby(by = df.State_Name)['Production','State_Name'].sum().reset_index().sort_values(by = 'Production', ascending = False).head(10)
Prod

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


State_Name    Production
15                       Kerala  9.788005e+10
1                Andhra Pradesh  1.732459e+10
27                   Tamil Nadu  1.207644e+10
30                Uttar Pradesh  3.234493e+09
3                         Assam  2.111752e+09
32                  West Bengal  1.397904e+09
17                  Maharashtra  1.263641e+09
14                    Karnataka  8.634298e+08
0   Andaman and Nicobar Islands  7.182232e+08
24                       Punjab  5.863850e+08

In [33]:
plt.figure(figsize= (15,15))
sns.barplot(x=df['Production'],y= df["State_Name"], orient='h');

**OBSERVATION :- Kerala is top state when we look at the quantum of Production for last 19.years.**

# Exploratory Analysis and Visualization

**Dataset has been preprocessed for next step that’s Exploring all the variables and 
their levels(for categorical variables) for extracting important insights which defines 
the Indian cultivation and how its progressing in future.
**

In [34]:
df.describe()

Crop_Year          Area    Production
count  242361.000000  2.423610e+05  2.423610e+05
mean     2005.625773  1.216741e+04  5.825034e+05
std         4.958285  5.085744e+04  1.706581e+07
min      1997.000000  1.000000e-01  0.000000e+00
25%      2002.000000  8.700000e+01  8.800000e+01
50%      2006.000000  6.030000e+02  7.290000e+02
75%      2010.000000  4.545000e+03  7.023000e+03
max      2015.000000  8.580100e+06  1.250800e+09

In [35]:
plt.hist(df.Area, bins = 5)

(array([2.42347e+05, 6.00000e+00, 5.00000e+00, 2.00000e+00, 1.00000e+00]),
 array([1.00000000e-01, 1.71602008e+06, 3.43204006e+06, 5.14806004e+06,
        6.86408002e+06, 8.58010000e+06]),
 <BarContainer object of 5 artists>)

In [36]:
plt.hist(df.Production, bins = 2)

(array([2.42304e+05, 5.70000e+01]),
 array([0.0000e+00, 6.2540e+08, 1.2508e+09]),
 <BarContainer object of 2 artists>)

Continuous variables Area and Production is highly skewed with lot of outliers.

In [37]:
#Zone-Wise Production - 1997-2014
north_india = ['Jammu and Kashmir', 'Punjab', 'Himachal Pradesh', 'Haryana', 'Uttarakhand', 'Uttar Pradesh', 'Chandigarh']
east_india = ['Bihar', 'Odisha', 'Jharkhand', 'West Bengal']
south_india = ['Andhra Pradesh', 'Karnataka', 'Kerala' ,'Tamil Nadu', 'Telangana']
west_india = ['Rajasthan' , 'Gujarat', 'Goa','Maharashtra']
central_india = ['Madhya Pradesh', 'Chhattisgarh']
north_east_india = ['Assam', 'Sikkim', 'Nagaland', 'Meghalaya', 'Manipur', 'Mizoram', 'Tripura', 'Arunachal Pradesh']
ut_india = ['Andaman and Nicobar Islands', 'Dadra and Nagar Haveli', 'Puducherry']

df.strip() helps to Remove spaces at the beginning and at the end of the string.

In [38]:
def get_zonal_names(row):
    if row['State_Name'].strip() in north_india:
        val = 'North Zone'
    elif row['State_Name'].strip()  in south_india:
        val = 'South Zone'
    elif row['State_Name'].strip()  in east_india:
        val = 'East Zone'
    elif row['State_Name'].strip()  in west_india:
        val = 'West Zone'
    elif row['State_Name'].strip()  in central_india:
        val = 'Central Zone'
    elif row['State_Name'].strip()  in north_east_india:
        val = 'NE Zone'
    elif row['State_Name'].strip()  in ut_india:
        val = 'Union Terr'
    else:
        val = 'No Value'
    return val

df['Zones'] = df.apply(get_zonal_names, axis=1)
df['Zones'].unique()

array(['Union Terr', 'South Zone', 'NE Zone', 'East Zone', 'North Zone',
       'Central Zone', 'West Zone'], dtype=object)

Using Zonal information, we can decipher the top zones are South India, North India and East India.

In [39]:
df.Zones.value_counts()

South Zone      53500
North Zone      49874
East Zone       43261
West Zone       33134
Central Zone    32972
NE Zone         28284
Union Terr       1336
Name: Zones, dtype: int64

**Using Zonal information, we can decipher the top zones are South India, North India and East India.**

In [40]:
crop=df['Crop']
def cat_crop(crop):
    for i in ['Rice','Maize','Wheat','Barley','Varagu','Other Cereals & Millets','Ragi','Small millets','Bajra','Jowar', 'Paddy','Total foodgrain','Jobster']:
        if crop==i:
            return 'Cereal'
    for i in ['Moong','Urad','Arhar/Tur','Peas & beans','Masoor',
              'Other Kharif pulses','other misc. pulses','Ricebean (nagadal)',
              'Rajmash Kholar','Lentil','Samai','Blackgram','Korra','Cowpea(Lobia)',
              'Other  Rabi pulses','Other Kharif pulses','Peas & beans (Pulses)','Pulses total','Gram']:
        if crop==i:
            return 'Pulses'
    for i in ['Peach','Apple','Litchi','Pear','Plums','Ber','Sapota','Lemon','Pome Granet',
               'Other Citrus Fruit','Water Melon','Jack Fruit','Grapes','Pineapple','Orange',
               'Pome Fruit','Citrus Fruit','Other Fresh Fruits','Mango','Papaya','Coconut','Banana']:
        if crop==i:
            return 'Fruits'
    for i in ['Bean','Lab-Lab','Moth','Guar seed','Soyabean','Horse-gram']:
        if crop==i:
            return 'Beans'
    for i in ['Turnip','Peas','Beet Root','Carrot','Yam','Ribed Guard','Ash Gourd ','Pump Kin','Redish','Snak Guard','Bottle Gourd',
              'Bitter Gourd','Cucumber','Drum Stick','Cauliflower','Beans & Mutter(Vegetable)','Cabbage',
              'Bhindi','Tomato','Brinjal','Khesari','Sweet potato','Potato','Onion','Tapioca','Colocosia']:
              if crop==i:
                return 'Vegetables'
    for i in ['Perilla','Ginger','Cardamom','Black pepper','Dry ginger','Garlic','Coriander','Turmeric','Dry chillies','Cond-spcs other']:
        if crop==i:
            return 'spices'
    for i in ['other fibres','Kapas','Jute & mesta','Jute','Mesta','Cotton(lint)','Sannhamp']:
        if crop==i:
            return 'fibres'
    for i in ['Arcanut (Processed)','Atcanut (Raw)','Cashewnut Processed','Cashewnut Raw','Cashewnut','Arecanut','Groundnut']:
        if crop==i:
            return 'Nuts'
    for i in ['other oilseeds','Safflower','Niger seed','Castor seed','Linseed','Sunflower','Rapeseed &Mustard','Sesamum','Oilseeds total']:
        if crop==i:
            return 'oilseeds'
    for i in ['Tobacco','Coffee','Tea','Sugarcane','Rubber']:
        if crop==i:
            return 'Commercial'

df['cat_crop']=df['Crop'].apply(cat_crop)

In [41]:
df["cat_crop"].value_counts()

Cereal        63283
Pulses        40898
oilseeds      33801
Vegetables    23154
spices        21638
Nuts          11472
Commercial    10561
fibres         9785
Beans          9115
Fruits         6153
Name: cat_crop, dtype: int64

**Looking at the new variable cat_crop, top frequency of crop types are Cereal, Pulses and oilseeds.**

In [42]:
data_explore = df.copy()

# Visualization on Important variables:
# a. Zonal distribution of crops:

In [43]:
fig, ax = plt.subplots(figsize=(15,10))
sns.barplot(data_explore.Zones.sort_values(ascending=True), data_explore.Production)
plt.yscale('log')
plt.title('Zone-Wise Production: Total')

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


Text(0.5, 1.0, 'Zone-Wise Production: Total')

**Production wise top zone is South India**

In [44]:
south_zone =  data_explore[(data_explore["Zones"] == 'South Zone')]
fig, ax = plt.subplots(figsize=(15,10))
sns.barplot(south_zone.State_Name, south_zone.Production,errwidth=0)
plt.yscale('log')
plt.title('Southern-Zone Production')

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


Text(0.5, 1.0, 'Southern-Zone Production')

**Top South Indian states are Kerala, Andhra Pradesh and Tamil Nadu**

# b. Crop wise Production status:

OVERALL CROP PRODUCTION

In [45]:
crop = data_explore.groupby(by='Crop')['Production'].sum().reset_index().sort_values(by='Production', ascending=False).head(10)
crop 
fig, ax = plt.subplots(figsize=(15,10))
sns.barplot(crop.Crop, crop.Production)
plt.yscale('log')
plt.title('Overall Crops vs Production')

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


Text(0.5, 1.0, 'Overall Crops vs Production')

**Top Crops Production wise are: Coconut, Sugarcane and Rice**

# c. Yearwise Production Status:

In [46]:
plt.tick_params(labelsize=10)
data_explore.groupby("Crop_Year")["Production"].agg("sum").plot.bar()

<AxesSubplot:title={'center':'Overall Crops vs Production'}, xlabel='Crop_Year', ylabel='Production'>

**High productive years are 2011, 2013 and 2014.**

# d. Season wise Production Status:


Season vs Production

In [47]:

df_season=data_explore.copy()
season = df_season.groupby(by='Season')['Production'].sum().reset_index().sort_values(by='Production', ascending=False).head(10)
season
fig, ax = plt.subplots(figsize=(15,10))
sns.barplot(season.Season, season.Production,errwidth=0)
plt.yscale('log')
plt.title('Seasonal Crops vs Production')

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


Text(0.5, 1.0, 'Seasonal Crops vs Production')

**Top crop categories which shows high production values are Whole Year(Annual growing plants), Kharif and Rabi crops. 
> It clearly shows these crops heavily dependent on seasonal monsoons.**

# e. Crop wise Production plot describing production values for all crop types.

In [48]:
plt.figure(figsize=(15,8))
plt.tick_params(labelsize=10)
data_explore.groupby("cat_crop")["Production"].agg("count").plot.bar()
plt.show()

**Top crop categories are Cereal, Pulses and Oilseeds.**

# f. State versus Crop Category versus Season plot:

In [49]:
plt.figure(figsize=(20,8))
sns.scatterplot(data=data_explore,x="State_Name",y="cat_crop",hue="Season")
plt.xticks(rotation=90)
plt.show()

Interesting facts:

* South zone:
i. Top producing state Kerela shows a abundance of whole year seasonal crops

1. North Zone:
ii. Top producing state Uttar Pradesh shows abundance of Kharif, Rabi and Summar crops

# g. Different proportion of Crop Categories for India


In [50]:
df1=data_explore["cat_crop"].value_counts()
df1.plot(radius=3,kind="pie",autopct="%1.1f",pctdistance=0.8)
plt.tick_params(labelsize=10)

# INSIGHTS DRAWN FROM THIS DATASET :-

# 1) State dominates in crop production with different categories of crops

Step 1: Making a crosstable using State Name and Crop categories

Step 2: Visualizing crosstable data in the form of stacked bar plot.


In [51]:
df_2 = pd.crosstab(data_explore['State_Name'], data_explore['cat_crop'])
df_2

cat_crop                     Beans  Cereal  Commercial  Fruits  Nuts  Pulses  \
State_Name                                                                     
Andaman and Nicobar Islands      0      20          15      16    37       9   
Andhra Pradesh                 386    2264         474     502   674    1336   
Arunachal Pradesh               26    1021         168       0    26      67   
Assam                            0    2952         854     920   400    2234   
Bihar                          280    6108         756     226   130    3731   
Chandigarh                       0      39           0       0     0      14   
Chhattisgarh                   646    1805         316     264   261    2087   
Dadra and Nagar Haveli           0     116          12       9     9      64   
Goa                              0      62          22      16    47      32   
Gujarat                        403    2466         372     157   683    1521   
Haryana                        108    1427         259      52   126     860   
Himachal Pradesh               179     726          67       0    54     530   
Jammu and Kashmir               12     562          42      24     7     307   
Jharkhand                        0     575          16       0     0     304   
Karnataka                     1096    5295         615     598  1470    2776   
Kerala                           3     819         236     437   536      13   
Madhya Pradesh                 962    5115         826     659   768    3993   
Maharashtra                    477    4009         458      83   868    2326   
Manipur                         31     151          40     228     4     160   
Meghalaya                      113     606         182     162   143     314   
Mizoram                         42     230         123       0    15     213   
Nagaland                       211    1054         160       0   144     873   
Odisha                         629    3871         607       0  1156    1760   
Puducherry                       0     198          30      73    98     101   
Punjab                         104    1123         216       0    75     728   
Rajasthan                      871    2634         518     257   444    2174   
Sikkim                          72     391           0       8     0     136   
Tamil Nadu                     479    2680         623     992  1076    1466   
Telangana                      259    1365         250     201   338     882   
Tripura                          0     240          80       0   119     469   
Uttar Pradesh                 1112    9719        1741     269   958    6549   
Uttarakhand                    360    1423         127       0    76    1236   
West Bengal                    254    2217         356       0   730    1633   

cat_crop                     Vegetables  fibres  oilseeds  spices  
State_Name                                                         
Andaman and Nicobar Islands          20       0        11      52  
Andhra Pradesh                     1046     333      1101     802  
Arunachal Pradesh                   257       0       343     637  
Assam                              1781    1284      2097    1338  
Bihar                              1775     924      2504    1396  
Chandigarh                           26       0         7       0  
Chhattisgarh                       1143     535      1496    1288  
Dadra and Nagar Haveli                0      13        30       1  
Goa                                   0       0         0      12  
Gujarat                             473     327      1029     512  
Haryana                             463     257       543     248  
Himachal Pradesh                    214      37       236     345  
Jammu and Kashmir                   196      44       233     115  
Jharkhand                           247       0       124       0  
Karnataka                          1763     605      3135    2588  
Kerala                              636    

In [52]:
df_2.plot(kind='bar', stacked=True, figsize = (16,8));

**Uttar Pradesh is topping in producing more crop categories than any other Indian state**

# 2) Crop is seen in high frequency and when and where is it grown in India?
Step 1: value.count() on Crop variable to find the high frequency crop in the dataset.

Step 2: Making a season of data only for that crop

Step 3: Finding out the season when it is grown heavily

Step 4: Finding out which state predominately produces it

Step 5: Finding out which District produces this crop highly

Step 6: Finding out which year the production figures are high

Step 7: Finding out Area versus Production relationship for this crop production

In [53]:
data_explore["Crop"].value_counts()[:5]

Rice                 15082
Maize                13787
Moong(Green Gram)    10106
Urad                  9710
Sesamum               8821
Name: Crop, dtype: int64

In [54]:
rice_df = data_explore[data_explore["Crop"]=="Rice"]
print(rice_df.shape)
rice_df[:3]

(15082, 9)


State_Name District_Name  Crop_Year       Season  Crop  \
2   Andaman and Nicobar Islands      NICOBARS       2000  Kharif       Rice   
12  Andaman and Nicobar Islands      NICOBARS       2001  Kharif       Rice   
18  Andaman and Nicobar Islands      NICOBARS       2002  Kharif       Rice   

     Area  Production       Zones cat_crop  
2   102.0      321.00  Union Terr   Cereal  
12   83.0      300.00  Union Terr   Cereal  
18  189.2      510.84  Union Terr   Cereal

In [55]:
sns.barplot("Season","Production",data=rice_df);

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


In [56]:
plt.figure(figsize=(13,10))
sns.barplot("State_Name","Production",data=rice_df)
plt.xticks(rotation=90)
plt.show()

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


In [57]:
top_rice_pro_dis = rice_df.groupby("District_Name")["Production"].sum().reset_index().sort_values(
    by='Production',ascending=False)
top_rice_pro_dis[:10]
sum_max = top_rice_pro_dis["Production"].sum()
top_rice_pro_dis["precent_of_pro"] = top_rice_pro_dis["Production"].map(lambda x:(x/sum_max)*100)
top_rice_pro_dis[:10]

District_Name  Production  precent_of_pro
58        BARDHAMAN  34239976.0        2.132707
374  MEDINIPUR WEST  29192719.0        1.818328
612   WEST GODAVARI  27845309.0        1.734402
169   EAST GODAVARI  24690929.0        1.537925
494         SANGRUR  24448000.0        1.522794
325         KRISHNA  20280606.0        1.263219
90          BIRBHUM  19753571.0        1.230391
347        LUDHIANA  18950000.0        1.180339
386     MURSHIDABAD  18403217.0        1.146282
214          GUNTUR  18245831.0        1.136479

In [58]:
plt.figure(figsize=(18,12))
sns.barplot("District_Name","Production",data=top_rice_pro_dis[:10])
plt.xticks(rotation=90)
plt.show()

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


In [59]:
plt.figure(figsize=(15,10))
sns.barplot("Crop_Year","Production",data=rice_df)
plt.xticks(rotation=45)
plt.show()

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


In [60]:
sns.jointplot("Area","Production",data=rice_df,kind="reg")

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


**Rice is grown heavily when we look the frequency of crops in India.**

**Rice needs Winter for it mature.**

**Statewise Punjab dominates in rice production.**

**District wise its BARDHAMAN(2.13%), MEDINIPUR WEST(1.8%) and WEST GODAVARI(1.73%) which contributes to total rice production.**

**Yearwise 2014 is the year when production reached the peak production.**

**Correlation between Area and Production shows high production is directly proportional to Area under cultivation.**

# 3) states ranks high in area wise crop production in India? Substantiate with facts and Figures.
Step 1: Find the state where Area under crop production is high and get top 10 states

Step 2: Make a subset of the data with the above conditional data

Step 3: Look the cultivation status of these states yearwise

In [61]:
df = data_explore.groupby(by='State_Name')['Area'].sum().reset_index().sort_values(by='Area', ascending=False)
df.head()

fig, ax = plt.subplots(figsize=(25,10))
sns.barplot(df.State_Name.head(10), df.Area.head(10), errwidth=0)
plt.title('Agricultural Area Distribution - India')
df.head(10)

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


State_Name          Area
30   Uttar Pradesh  4.336223e+08
16  Madhya Pradesh  3.297913e+08
17     Maharashtra  3.221860e+08
25       Rajasthan  2.687882e+08
32     West Bengal  2.154030e+08
14       Karnataka  2.029086e+08
9          Gujarat  1.549261e+08
1   Andhra Pradesh  1.315073e+08
4            Bihar  1.282695e+08
24          Punjab  1.267152e+08

In [62]:
df = data_explore.groupby(by='State_Name')['Area'].sum().reset_index().sort_values(by='Area', ascending=False)
df = df.head(5)

fig, ax = plt.subplots(figsize=(25,30), sharey='col')
count = 1

for state in df.State_Name.unique():
    plt.subplot(len(df.State_Name.unique()),1,count)
    sns.lineplot(data_explore[data_explore.State_Name==state]['Crop_Year'],data_explore[data_explore.State_Name==state]['Production'], ci=None)
    plt.subplots_adjust(hspace=0.6)
    plt.title(state)
    count+=1;

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning
/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning
/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning
/opt/conda/lib/python3.7/site-package

**Top cultivating states based on the Cultivation area are: Uttar Pradesh(4.33e+08), Madhya Pradesh(3.29e+08) and Maharashtra(3.22e+08)**

**Yearwise Statues of these States:**

**a. Uttar Pradesh: High Production was seen in 2005 and after that it's been reducing gradually.**

**b. Madhya Pradesh:1998 showed a high production and then there was gradual reduction but it picked up and 2012 also showed a peak in Production**

**c. Maharashtra:Production went down drastically in 2006 and again the levels went up and hit a high peak after 2007**

**d. Rajasthan: the production hit a all time low in the year 2002 and then picked up by 2010**

**e. West Bengal:the production hit a peak around 2006 but it has hit a low after 2007 and never recovered back.**

# 4) Top crops grown in Northern parts of India.
Step 1: Extract North zone data as a subset

Step 2: Explore the top states of North which show high crop production stats

Step 3: Explore the top crops grown in North India


In [63]:
data_explore.Zones.value_counts()

South Zone      53500
North Zone      49874
East Zone       43261
West Zone       33134
Central Zone    32972
NE Zone         28284
Union Terr       1336
Name: Zones, dtype: int64

In [64]:
North_zone =  data_explore[(data_explore["Zones"] == 'North Zone')]
fig, ax = plt.subplots(figsize=(15,10))
sns.barplot(North_zone.State_Name, North_zone.Production,errwidth=0)
plt.xticks(rotation=75);
plt.yscale('log')
plt.title('Northern-Zone Production')

North_zone.groupby(by='State_Name')['Production'].sum().reset_index().sort_values(by='Production', ascending=False)

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


State_Name    Production
5       Uttar Pradesh  3.234493e+09
4              Punjab  5.863850e+08
1             Haryana  3.812739e+08
6         Uttarakhand  1.321774e+08
2    Himachal Pradesh  1.780517e+07
3  Jammu and Kashmir   1.329102e+07
0          Chandigarh  6.395650e+04

In [65]:
df3 = North_zone.groupby(by='Crop')['Production'].sum().reset_index().sort_values(by='Production', ascending=False).head(10)

fig, ax = plt.subplots(figsize=(15,10))
sns.barplot(df3.Crop, df3.Production,errwidth=0)
plt.xticks(rotation=75);
plt.yscale('log')
plt.title('North Zone Crops vs Production')

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


Text(0.5, 1.0, 'North Zone Crops vs Production')

* Production wise top states of North zone are:*
1. Punjab(5.86e+08)
2. Uttar Pradesh(3.23e+09), and
3. Haryana(3.81e+08)
* Top crops of these states are:
1. Sugarcane,
2. Wheat and
3. Rice

# 5) Top crop of South India is Coconut, Finding  out that status of Coconut production in India.
Step 1: Drawing a subset of data for Coconut Production in India

Step 2: Finding the conducive season for coconut production

Step 3: Exploring the states involved in coconut production

Step 4: Exploring the southern district involved in coconut production

Step 5: Finding the cultivation status of coconut yearwise

Step 6: Finding the Area under cultivation in South India

In [66]:
coc_df = data_explore[data_explore["Crop"]=="Coconut "]
print(coc_df.shape)
coc_df[:3]

(1958, 9)


State_Name District_Name  Crop_Year       Season  \
5   Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
14  Andaman and Nicobar Islands      NICOBARS       2001  Whole Year    
23  Andaman and Nicobar Islands      NICOBARS       2002  Whole Year    

        Crop     Area  Production       Zones cat_crop  
5   Coconut   18168.0  65100000.0  Union Terr     None  
14  Coconut   18190.0  64430000.0  Union Terr     None  
23  Coconut   18240.0  67490000.0  Union Terr     None

In [67]:
sns.barplot("Season","Production",data=coc_df)

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


<AxesSubplot:title={'center':'North Zone Crops vs Production'}, xlabel='Season', ylabel='Production'>

In [68]:
plt.figure(figsize=(13,10))
sns.barplot("State_Name","Production",data=coc_df)
plt.xticks(rotation=90)
plt.show()

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


In [69]:
top_coc_pro_dis = coc_df.groupby("District_Name")["Production"].sum().reset_index().sort_values(
    by='Production',ascending=False)
top_coc_pro_dis[:5]
sum_max = top_coc_pro_dis["Production"].sum()
top_coc_pro_dis["precent_of_pro"] = top_coc_pro_dis["Production"].map(lambda x:(x/sum_max)*100)
top_coc_pro_dis[:5]

District_Name    Production  precent_of_pro
77            KOZHIKODE  1.527871e+10       11.754512
86           MALAPPURAM  1.451252e+10       11.165052
129  THIRUVANANTHAPURAM  1.001337e+10        7.703678
131            THRISSUR  9.920739e+09        7.632416
64               KANNUR  9.780310e+09        7.524379

In [70]:
plt.figure(figsize=(18,12))
sns.barplot("District_Name","Production",data=top_coc_pro_dis[:5])
plt.xticks(rotation=90)
plt.show()

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


In [71]:
plt.figure(figsize=(15,10))
sns.barplot("Crop_Year","Production",data=coc_df)
plt.xticks(rotation=45)
#plt.legend(rice_df['State_Name'].unique())
plt.show()

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning


In [72]:
sns.jointplot("Area","Production",data=coc_df,kind="reg")

/opt/conda/lib/python3.7/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning
/opt/conda/lib/python3.7/site-packages/seaborn/axisgrid.py:1670: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  f = plt.figure(figsize=(height, height))


1. Coconut cultivation is yearlong and doesn't get restricted to any particular seasons

2. Top states involved in coconut production are: Kerala, Andhra Pradesh and Tamil Nadu

3. Top districts featuring in coconut production is KOZHIKODE(11.75%), MALAPPURAM(11.16%) and THIRUVANANTHAPURAM(7.7%)

4. Yearwise coconut cultivation is strong and its increasing healthly

5. High coconut cultivation is directly proportional to area under cultivation.

# Inferences and Conclusion

I started with 246091 samples wih 7 columns. Production Variable had 3730 (1.5% of total sample size) missing values which was dropped and working dataset has 242361 sample size. Also checked for multicollinearity of variables using heatmap.

**Univarate Analysis:**
1. State_Name: 33 Names including Union territories. Top states contributing to dataset are Uttar Pardesh, Madhya Pradesh and Karnataka.
2. District_Name: 646 districts are represented in the dataset and Top contributors are Tumkur, Belgaum and Bijapur from Karnataka.
3. Crop_Year: Dataset represents data for 19 years from 1997 to 2015 and maximum data from 2003, 2002 & 2007.
4. Season: we see six seasons with maximum data from Kharif, Rabi and Whole year.
5. Crop: we data for 124 different crops with top occurrence from Rice, Maize and Moong(Green Gram).
6. Area: Huge margin area used for production from 1 to 8580100 unit area. Distribution is highly right        skewed due to lot of outliers.
7. Production: Production value ranges from 0 to 1.25e+09 and Distribution is highly right skewed due to lot of outliers.

**Bivarate Analysis:**
1. State_Name Vs Production: Top states are Kerala, Andhara Pradesh and Tamil Nadu.

**New Variables created:-**

a. Zones: A new variable was created based on 33 State_Name. States were divided bucketed into North Zone, South Zone, East Zone, West Zone, Central Zone, NE Zone and Union Terr.

Dataset has more data coming from South, North and East zones.

b. Cat_crop: 124 crops were divided into Cereal, Pulses, oilseeds, Vegetables, spices, Nuts, Commercial, fibres, Beans, Fruits. Dataset shows top categories are Cereal, Pulses and oilseeds.

**Visualization done on:**
a. Zonal distribution of crops:

Production wise top zone is South zone with Kerala topping it's high crop production.
b. Crop wise Production status:

Production wise top crop type are Coconut, Sugarcane and Rice.
c. Yearwise Production Status:

Total Production hit peak in the year 2011 and 2013.
d. Season wise Production Status:

Top crop categories which shows high production values are Whole Year(Annual growing plants),Kharif and Rabi crops. It clearly shows these crops heavily dependent on seasonal monssons.
e. Crop Category wise Production Status:

Top crop categories are Cereal, Pulses and Oilseeds.
f. State versus crop Category versus Season Status:

Top producing state Kerela shows a abundance of whole year seasonal crops and
Top producing state Uttar Pradesh shows abundance of Kharif, Rabi and Summar crops.
g. Different Proportion of crop Categories Status:

Top Crop Categories are Cereal(27.5), Pulses(17.8) and oilseeds(14.7) and these crops contribute towards 60% of total crop production.